# Generated by Django 4.2.10 on 2024-02-28 19:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendeer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events_to_Attendees',
            new_name='EventsAttendees',
        ),
    ]
